ubuntu-16.04:
    build: ./
    container_name: "ubuntu-16.04"
    hostname: "ubuntu-16-04"
    volumes:
        - /Users/user:/home/user:rw
    ports:
        - "2222:22"
    expose:
        - "22"
    cap_add:
        - SYS_PTRACE
    security_opt:
        - seccomp:unconfined